name: build cloud-select

on:

  # Publish packages on release
  release:
    types: [published]

  pull_request: []

  # On push to main we build and deploy images
  push:
    branches:
    - main

jobs:
  build:
    permissions:
      packages: write

    runs-on: ubuntu-latest
    name: Build
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Container
      run: docker build -t ghcr.io/converged-computing/cloud-select:latest .

    - name: GHCR Login
      if: (github.event_name != 'pull_request')
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag and Push Release Image
      if: (github.event_name == 'release')
      run: |
        tag=${GITHUB_REF#refs/tags/}
        echo "Tagging and releasing ghcr.io/converged-computing/cloud-select:${tag}"
        docker tag ghcr.io/converged-computing/cloud-select:latest ghcr.io/converged-computing/cloud-select:${tag}
        docker push ghcr.io/converged-computing/cloud-select:${tag}

    - name: Deploy
      if: (github.event_name != 'pull_request')
      run: docker push ghcr.io/converged-computing/cloud-select:latest
