name: test cloud-select

on:
  pull_request: []

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup black linter
      run: conda create --quiet --name black pytest

    - name: Check Spelling
      uses: crate-ci/typos@7ad296c72fa8265059cc03d1eda562fbdfcd6df2 # v1.9.0
      with:
        files: ./README.md ./docs/*.md

    - name: Lint and format Python code
      run: |
        export PATH="/usr/share/miniconda/bin:$PATH"
        source activate black
        pip install -r .github/dev-requirements.txt
        pre-commit run --all-files

    - name: Test
      env:
        ORAS_USER: ${{ github.actor }}
        ORAS_PASS: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export PATH="/usr/share/miniconda/bin:$PATH"
        source activate black
        pip install -e .[all]
        pytest -xs cloudselect/tests/test*.py
